# Copyright (c) 2020 Patrick Diehl
#               
#
# Distributed under the Boost Software License, Version 1.0. (See accompanying
# file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

version: 2
jobs:
    deploy:
      machine:
        image: ubuntu-2004:202008-01
      environment:
        IMAGE_FOLDER_NAME: Docker
        IMAGE_NAME: diehlpk/nlmech:stable
      steps:
        - checkout
        - run:
           name: Build Docker image
           command: |
              docker build -t ${IMAGE_NAME} ${IMAGE_FOLDER_NAME} ./Fedora
              docker images
        - run: 
           name: Deploy to DockerHub
           command: |
             if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login -u $DOCKER_USER -p $DOCKER_PASS
                docker push ${IMAGE_NAME}
             fi
        - run: 
           name: Deploy to GitHub
           command: |
              if [ "${CIRCLE_BRANCH}" == "master" ]; then
                docker login docker.pkg.github.com --username diehlpk -p ${TOKEN}
                docker tag ${IMAGE_NAME} docker.pkg.github.com/nonlocalmodels/nlmech/stable:latest
                docker push docker.pkg.github.com/nonlocalmodels/nlmech/nlmech:stable
              fi
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - deploy